apisix:
  enable_admin: true
  admin:
    listen: 0.0.0.0:9180  # Puerto del admin de APISIX

  # Configuración de rutas
  routes:
    - uri: /users/*
      upstream:
        nodes:
          - host: "${BACK_SV_USERS_LOCAL}"
            port: "${BACK_SV_USERS_PORT}"
            weight: 1
        type: roundrobin
      name: back-sv-users

    - uri: /models/*
      upstream:
        nodes:
          - host: "${BACK_SV_MODELS_LOCAL}"
            port: "${BACK_SV_MODELS_PORT}"
            weight: 1
        type: roundrobin
      name: back-sv-models
