# Ruta de prueba
- uri: /audio/test
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

# Rutas de usuarios
- uri: /users/register
  methods:
    - POST
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/profile
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/name
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/update-name
  methods:
    - PATCH
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/email
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/update-email
  methods:
    - PATCH
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/notifications
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/update-notifications
  methods:
    - PATCH
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/profile-pic
  methods:
    - GET
    - PATCH
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/privacy
  methods:
    - GET
    - PATCH
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

- uri: /users/delete
  methods:
    - DELETE
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_USERS_HOST}:${BACK_SV_USERS_PORT}": 1
    pass_host: pass

# Rutas de transcripciones
- uri: /users/transcriptions
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/{transcription_id}
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/by-emotion/{emotion}
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/by-sentiment/{sentiment}
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/by-topic/{topic}
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/by-date/{date}
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/by-hour/
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/filter
  methods:
    - GET
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/add-transcription
  methods:
    - POST
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/delete-transcription/{transcription_id}
  methods:
    - POST
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass

- uri: /users/transcriptions/delete-all-transcriptions
  methods:
    - POST
  plugins:
    openid-connect:
      bearer_only: true
      use_jwks: true
      client_id: ${AUTH0_CLIENT_ID}
      client_secret: ${AUTH0_CLIENT_SECRET}
      discovery: ${AUTH0_DISCOVERY_URL}
      scope: "openid profile"
  upstream:
    type: roundrobin
    nodes:
      "${BACK_SV_MODELS_HOST}:${BACK_SV_MODELS_PORT}": 1
    pass_host: pass
